[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "FRC Tutorials"
authors = [{name = "WPI Tutorials", email = "tutorials@frc"}]
dynamic = ["version", "description"]
